name: Deploy with Jekyll (Fallback)

on:
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-fallback"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create Jekyll site
        run: |
          # Create a minimal Jekyll site structure
          mkdir -p _site
          cp index.html _site/
          cp *.js _site/ 2>/dev/null || true
          cp *.css _site/ 2>/dev/null || true
          cp *.json _site/ 2>/dev/null || true
          cp *.png _site/ 2>/dev/null || true
          
          if [ -d "icons" ]; then
            cp -r icons _site/
          fi
          
          # Create minimal Jekyll config
          cat > _site/_config.yml << EOF
          title: AudioPhotoJournal
          description: A multimedia journaling web app
          baseurl: "/AudioVisualJournal"
          url: "https://TravisWagnerPersonal.github.io"
          markdown: kramdown
          highlighter: rouge
          permalink: pretty
          EOF
          
          echo "Jekyll site created:"
          ls -la _site/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 